### ISSUE TITLE
Review the list of potential speakers

### ISSUE THREAD

**Issue by samgdotson** [ansuiuc/uiuc-ans-proposal#1]
I wanted to include some people from plasma physics as well as people from nuclear. Jeremy Mettler will be asking David Ruzic about potential speakers from that end.

Can be closed when the list of speakers is approved. 

@katyhuff

**Comment by katyhuff** [comment]
Are you trying to assign this to me? Or just mentioning me? 
Should this be assigned to Jeremy (as it's an action for him to compile possible plasma speakers)? 
Should it be assigned to me (is it an action for me to review a future list?)?

**Comment by samgdotson** [comment]
Yes, it should be assigned to you both. However, I was unable to assign anyone but myself, until now.

**Comment by samgdotson** [comment]
@tokamak990 
mentioning jeremy

**Comment by katyhuff** [comment]
I made some comments in the doc.
