### ISSUE TITLE
Second Draft

### ISSUE THREAD

**Issue by samgdotson** [ansuiuc/uiuc-ans-proposal#16]
We are waiting on a few pieces of content: 
- Graphical schedule by day (Jeremy)
- Letter from David Ruzic (Jeremy)
- Letter from Rizwan Uddin (Barb)
- Letter from Dean of Engineering (??)

Otherwise, I feel that this document is complete, correct, and ready for a final review.

**Comment by katyhuff** [comment]
![image](https://user-images.githubusercontent.com/393899/65989417-456f9280-e44f-11e9-9f71-0518382d82d4.png)
