### ISSUE TITLE
Transfer ownership of this repository to ansuiuc

### ISSUE THREAD

**Issue by katyhuff** [ansuiuc/uiuc-ans-proposal#3]
The ansuiuc org is the right place to put this repository because :  
 
- there is already a proposal outline there, though I see you have duplicated efforts somewhat already, so maybe just ignore it.
- we can add members to it freely, allowing everyone to collaborate without the repository management being owned by an individual.
- in a personal repository, assigning people to issues, merging PRs, etc. is managed by that individual -- the org exists so that ANS members at UIUC can collaborate on collaborative things (like those administrative tasks)
- posterity.

This issue can be closed when this repository's [ownership has been transferred](https://help.github.com/en/articles/transferring-a-repository) to ansuiuc. 

Consider also : [archiving](https://help.github.com/en/articles/about-archiving-repositories) the old ans conference proposal repository that already exists in that repository.

**Comment by katyhuff** [comment]
@samgdotson : Since this is your repository and I am not a collaborator, I cannot assign you to this issue, so I am mentioning you here.

**Comment by samgdotson** [comment]
Done

**Comment by katyhuff** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/849e65c4-2dc2-4877-8981-2dc04080868a-aef391d1-ee2a-4ffc-b1c7-1c24444a7cae-v1.png?transparent=1&palette=1&width=246)
